Update aky-updatecheck

diff --git a/bin/aky-updatecheck b/bin/aky-updatecheck
--- a/bin/aky-updatecheck
+++ b/bin/aky-updatecheck
@@ -13,7 +13,7 @@
   if [ ! -s "/usr/local/aky/download-helper" ]; then
     echo "${redEcho}Error:${normalEcho} Please install 'aky Patch Management', download-helper was not found!" && exit 1
   elif [ ! -s "/usr/local/bin/jq" ]; then
-    echo "${redEcho}Error:${normalEcho} Please install 'jq' command-line JSON processor (https://stedolan.github.io/jq/)!"
+    echo "${redEcho}Error:${normalEcho} Please install 'jq' command-line JSON processor (https://stedolan.github.io/jq/)!" && exit 1
   fi
   
   tmpFolder=$(getconf DARWIN_USER_CACHE_DIR)
