Update appstorelookup

diff --git a/bin/appstorelookup b/bin/appstorelookup
--- a/bin/appstorelookup
+++ b/bin/appstorelookup
@@ -2,8 +2,8 @@
 
 adam_id="${1}"
 
-if [ ! -n "${adam_id}" ]; then
-	echo "Error: Please provide ADAM ID" && exit 1
+if [ -z "${adam_id}" ]; then
+  echo "Error: Please provide ADAM ID" && exit 1
 fi
 
 curl -s -o "/tmp/1.txt.js" "https://itunes.apple.com/lookup?id=${adam_id}&country=ch"
