Update gmcfa

diff --git a/bin/gmcfa b/bin/gmcfa
--- a/bin/gmcfa
+++ b/bin/gmcfa
@@ -1,96 +1,95 @@
 #!/bin/bash
-  
-  prog_name=$(/usr/bin/basename ${0})
-  prog_version="2.0"
-  
-  logging_standard() {
-    
-    log_file="/tmp/${prog_name}.log"
-    
-    [ ! -s "${log_file}" ] && touch "${log_file}"
-    
-    exec 3>&1 1>>${log_file} 2>&1
-    
-  }
-  
-  console() {
-    printf "%s\n" "$*" 1>&3
-  }
-  
-  logging_standard
-  
-  bld=$(/usr/bin/tput bold)
-  
-  grn=$(/usr/bin/tput setaf 2)
-  mag=$(/usr/bin/tput setaf 5)
-  blu=$(/usr/bin/tput setaf 4)
-  
-  uln=$(/usr/bin/tput smul)
-  sto=$(/usr/bin/tput smso)
-  clr=$(/usr/bin/tput sgr0)
-  
-  if [ -z "${1}" ]; then
-    echo "Error: Invalid argument" && exit 1
-  fi
-  
-  cask="${1}"
-  
-  check_httpcode_cask=$(/usr/bin/curl -sL -w "%{http_code}" "https://raw.githubusercontent.com/Homebrew/homebrew-cask/master/Casks/${cask}.rb" -o /dev/null)
-  check_httpcode_cask_drivers=$(/usr/bin/curl -sL -w "%{http_code}" "https://raw.githubusercontent.com/Homebrew/homebrew-cask-drivers/master/Casks/${cask}.rb" -o /dev/null)
-  check_httpcode_cask_versions=$(/usr/bin/curl -sL -w "%{http_code}" "https://raw.githubusercontent.com/Homebrew/homebrew-cask-versions/master/Casks/${cask}.rb" -o /dev/null)
-  
-  if [ ${check_httpcode_cask} != 200 ] && [ ${check_httpcode_cask_drivers} != 200 ] && [ ${check_httpcode_cask_versions} != 200 ]; then
-    console "Error: '${cask}' is not a valid cask" && exit 1
-  fi
-  
-  console "${bld}cask${clr}        ${sto}${cask}${clr}"
-  
-  app=$(/usr/local/bin/brew cask _stanza app ${cask})
-  
-  if [ ! -z "${app}" ]; then
-    console "${bld}app${clr}         ${app}"
-  fi
-  
-  pkg=$(/usr/local/bin/brew cask _stanza pkg ${cask})
-  
-  if [ ! -z "${pkg}" ]; then
-    console "${bld}pkg${clr}         ${pkg}"
-  fi
-  
-  suite=$(/usr/local/bin/brew cask _stanza suite ${cask})
-  
-  if [ ! -z "${suite}" ]; then
-    console "${bld}suite${clr}       ${suite}"
-  fi
-  
-  version=$(/usr/local/bin/brew cask _stanza version ${cask})
-  url=$(/usr/local/bin/brew cask _stanza url ${cask})
-  
-  console "${bld}version${clr}     ${mag}${version}${clr}"
-  console "${bld}url${clr}         ${url}"
-  
-  sha265=$(/usr/local/bin/brew cask _stanza sha256 ${cask})
-  
-  console "${bld}sha265${clr}      ${grn}${sha265}${clr}"
-  
-  appcast=$(/usr/local/bin/brew cask _stanza appcast ${cask})
-  appcast_checkpoint=$(/usr/local/bin/brew cask _stanza appcast ${cask})
-  
-  if [ ! -z "${appcast}" ]; then
-    checkpoint=$(/usr/local/bin/appcast-checkpoint ${appcast_checkpoint})
-  fi
-  
-  if [ ! -z "${appcast}" ]; then
-    console "${bld}appcast${clr}     ${appcast}"
-    console "${bld}checkpoint${clr}  ${blu}${checkpoint}${clr}"
-  fi
-  
-  pkgutil=$(/usr/local/bin/brew cask _stanza pkgutil ${cask})
-  
-  if [ ! -z "${pkgutil}" ]; then
-    console "${bld}pkgutil${clr}   ${pkgutil}"
-  fi
-  
-  homepage=$(/usr/local/bin/brew cask _stanza homepage ${cask})
-  
-  console "${bld}homepage${clr}    ${uln}${homepage}${clr}"
+
+prog_name=$(basename "${0}")
+
+logging_standard() {
+
+  log_file="/tmp/${prog_name}.log"
+
+  [ ! -s "${log_file}" ] && touch "${log_file}"
+
+  exec 3>&1 1>>"${log_file}" 2>&1
+
+}
+
+console() {
+  printf "%s\n" "$*" 1>&3
+}
+
+logging_standard
+
+bld=$(/usr/bin/tput bold)
+
+grn=$(/usr/bin/tput setaf 2)
+mag=$(/usr/bin/tput setaf 5)
+blu=$(/usr/bin/tput setaf 4)
+
+uln=$(/usr/bin/tput smul)
+sto=$(/usr/bin/tput smso)
+clr=$(/usr/bin/tput sgr0)
+
+if [ -z "${1}" ]; then
+  echo "Error: Invalid argument" && exit 1
+fi
+
+cask="${1}"
+
+check_httpcode_cask=$(/usr/bin/curl -sL -w "%{http_code}" "https://raw.githubusercontent.com/Homebrew/homebrew-cask/master/Casks/${cask}.rb" -o /dev/null)
+check_httpcode_cask_drivers=$(/usr/bin/curl -sL -w "%{http_code}" "https://raw.githubusercontent.com/Homebrew/homebrew-cask-drivers/master/Casks/${cask}.rb" -o /dev/null)
+check_httpcode_cask_versions=$(/usr/bin/curl -sL -w "%{http_code}" "https://raw.githubusercontent.com/Homebrew/homebrew-cask-versions/master/Casks/${cask}.rb" -o /dev/null)
+
+if [ "${check_httpcode_cask}" != 200 ] && [ "${check_httpcode_cask_drivers}" != 200 ] && [ "${check_httpcode_cask_versions}" != 200 ]; then
+  console "Error: '${cask}' is not a valid cask" && exit 1
+fi
+
+console "${bld}cask${clr}        ${sto}${cask}${clr}"
+
+app=$(/usr/local/bin/brew cask _stanza app "${cask}")
+
+if [ -n "${app}" ]; then
+  console "${bld}app${clr}         ${app}"
+fi
+
+pkg=$(/usr/local/bin/brew cask _stanza pkg "${cask}")
+
+if [ -n "${pkg}" ]; then
+  console "${bld}pkg${clr}         ${pkg}"
+fi
+
+suite=$(/usr/local/bin/brew cask _stanza suite "${cask}")
+
+if [ -n "${suite}" ]; then
+  console "${bld}suite${clr}       ${suite}"
+fi
+
+version=$(/usr/local/bin/brew cask _stanza version "${cask}")
+url=$(/usr/local/bin/brew cask _stanza url "${cask}")
+
+console "${bld}version${clr}     ${mag}${version}${clr}"
+console "${bld}url${clr}         ${url}"
+
+sha265=$(/usr/local/bin/brew cask _stanza sha256 "${cask}")
+
+console "${bld}sha265${clr}      ${grn}${sha265}${clr}"
+
+appcast=$(/usr/local/bin/brew cask _stanza appcast "${cask}")
+appcast_checkpoint=$(/usr/local/bin/brew cask _stanza appcast "${cask}")
+
+if [ -n "${appcast}" ]; then
+  checkpoint=$(/usr/local/bin/appcast-checkpoint "${appcast_checkpoint}")
+fi
+
+if [ -n "${appcast}" ]; then
+  console "${bld}appcast${clr}     ${appcast}"
+  console "${bld}checkpoint${clr}  ${blu}${checkpoint}${clr}"
+fi
+
+pkgutil=$(/usr/local/bin/brew cask _stanza pkgutil "${cask}")
+
+if [ -n "${pkgutil}" ]; then
+  console "${bld}pkgutil${clr}   ${pkgutil}"
+fi
+
+homepage=$(/usr/local/bin/brew cask _stanza homepage "${cask}")
+
+console "${bld}homepage${clr}    ${uln}${homepage}${clr}"
