Update gmcfa

diff --git a/bin/gmcfa b/bin/gmcfa
--- a/bin/gmcfa
+++ b/bin/gmcfa
@@ -1,65 +1,65 @@
 #!/bin/bash
-	
-	prog_name=$(/usr/bin/basename ${0})
-	prog_version="2.0"
-	
-	logging_standard() {
-		
-		log_file="/tmp/${prog_name}.log"
-		
-		[ ! -s "${log_file}" ] && touch "${log_file}"
-		
-		exec 3>&1 1>>${log_file} 2>&1
-		
-	}
-	
-	console() {
-		printf "%s\n" "$*" 1>&3
-	}
-	
-	logging_standard
-	
-	bld=$(/usr/bin/tput bold)
-	
-	grn=$(/usr/bin/tput setaf 2)
-	mag=$(/usr/bin/tput setaf 5)
-	blu=$(/usr/bin/tput setaf 4)
-	
-	uln=$(/usr/bin/tput smul)
-	sto=$(/usr/bin/tput smso)
-	clr=$(/usr/bin/tput sgr0)
-	
-	cask="${1}"
+  
+  prog_name=$(/usr/bin/basename ${0})
+  prog_version="2.0"
+  
+  logging_standard() {
+    
+    log_file="/tmp/${prog_name}.log"
+    
+    [ ! -s "${log_file}" ] && touch "${log_file}"
+    
+    exec 3>&1 1>>${log_file} 2>&1
+    
+  }
+  
+  console() {
+    printf "%s\n" "$*" 1>&3
+  }
+  
+  logging_standard
+  
+  bld=$(/usr/bin/tput bold)
+  
+  grn=$(/usr/bin/tput setaf 2)
+  mag=$(/usr/bin/tput setaf 5)
+  blu=$(/usr/bin/tput setaf 4)
+  
+  uln=$(/usr/bin/tput smul)
+  sto=$(/usr/bin/tput smso)
+  clr=$(/usr/bin/tput sgr0)
+  
+  cask="${1}"
 
-	if [ -z "${1}" ]; then
-		echo "Error: Invalid argument" && exit 1
-	fi
-	
-	app=$(/usr/local/bin/brew cask _stanza app ${cask})
-	version=$(/usr/local/bin/brew cask _stanza version ${cask})
-	url=$(/usr/local/bin/brew cask _stanza url ${cask})
-	sha265=$(/usr/local/bin/brew cask _stanza sha256 ${cask})
-	appcast=$(/usr/local/bin/brew cask _stanza appcast ${cask})
-	appcast_checkpoint=$(/usr/local/bin/brew cask _stanza appcast ${cask})
-	homepage=$(/usr/local/bin/brew cask _stanza homepage ${cask})
-	
-	if [ ! -z "${appcast}" ]; then
-		checkpoint=$(/usr/local/bin/appcast-checkpoint ${appcast_checkpoint})
-	fi
-	
-	console "${bld}cask${clr}        ${sto}${cask}${clr}"
-	
-	if [ ! -z "${app}" ]; then
-		console "${bld}app${clr}         ${app}"
-	fi
-	
-	console "${bld}version${clr}     ${mag}${version}${clr}"
-	console "${bld}url${clr}         ${url}"
-	console "${bld}sha265${clr}      ${grn}${sha265}${clr}"
-	
-	if [ ! -z "${appcast}" ]; then
-		console "${bld}appcast${clr}     ${appcast}"
-		console "${bld}checkpoint${clr}  ${blu}${checkpoint}${clr}"
-	fi
-	
-	console "${bld}homepage${clr}    ${uln}${homepage}${clr}"
+  if [ -z "${1}" ]; then
+    echo "Error: Invalid argument" && exit 1
+  fi
+  
+  app=$(/usr/local/bin/brew cask _stanza app ${cask})
+  version=$(/usr/local/bin/brew cask _stanza version ${cask})
+  url=$(/usr/local/bin/brew cask _stanza url ${cask})
+  sha265=$(/usr/local/bin/brew cask _stanza sha256 ${cask})
+  appcast=$(/usr/local/bin/brew cask _stanza appcast ${cask})
+  appcast_checkpoint=$(/usr/local/bin/brew cask _stanza appcast ${cask})
+  homepage=$(/usr/local/bin/brew cask _stanza homepage ${cask})
+  
+  if [ ! -z "${appcast}" ]; then
+    checkpoint=$(/usr/local/bin/appcast-checkpoint ${appcast_checkpoint})
+  fi
+  
+  console "${bld}cask${clr}        ${sto}${cask}${clr}"
+  
+  if [ ! -z "${app}" ]; then
+    console "${bld}app${clr}         ${app}"
+  fi
+  
+  console "${bld}version${clr}     ${mag}${version}${clr}"
+  console "${bld}url${clr}         ${url}"
+  console "${bld}sha265${clr}      ${grn}${sha265}${clr}"
+  
+  if [ ! -z "${appcast}" ]; then
+    console "${bld}appcast${clr}     ${appcast}"
+    console "${bld}checkpoint${clr}  ${blu}${checkpoint}${clr}"
+  fi
+  
+  console "${bld}homepage${clr}    ${uln}${homepage}${clr}"
