Update pkgfixer

diff --git a/bin/pkgfixer b/bin/pkgfixer
--- a/bin/pkgfixer
+++ b/bin/pkgfixer
@@ -1,60 +1,34 @@
 #!/bin/bash
   
-  currentuser=$(python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')
+  readonly progName=$(/usr/bin/basename ${0})
+  readonly progVersion="1.0"
   
-  if [ ! -z "${currentuser}" ]; then
+  tmpFolder=$(getconf DARWIN_USER_CACHE_DIR)
+  randString=$(/usr/bin/openssl rand -hex 5)
+  workDir="${tmpFolder}${randString}"
+  /bin/mkdir -p "${workDir}"
   
-    if [ -s "/Users/${currentuser}/.rnd" ]; then
-      
-      rm -rf "/Users/${currentuser}/.rnd"
-      
-    fi
-    
-  fi
+  expandFolder="${workDir}/expandFolder" && /bin/mkdir -p "${expandFolder}"
+  flattenFolder="${workDir}/flattenFolder" && /bin/mkdir -p "${flattenFolder}"
   
-  randstring=$(/usr/bin/openssl rand -hex 5)
-  
-  tmp="/private/tmp/${randstring}"
-  expand="${tmp}/expand"
-  flatten="${tmp}/flatten"
-  
-  /bin/mkdir -p "${tmp}"
-  /bin/mkdir -p "${expand}"
-  /bin/mkdir -p "${flatten}"
-    
-  arg="${1}"
+  PKGarg="${1}"
   
   if [ ! -z "${1}" ]; then
-    
     echo "Process '${1}'"
-    
   else
-    
-    echo "Error: Add PKG path as argument"
-    
-    exit 1
-    
+    echo "Error: Add PKG path as argument" && exit 1
   fi
   
-  /bin/cp -r "${arg}" "${tmp}"/
+  /bin/cp -r "${PKGarg}" "${workDir}/"
   
-  if [ ! -z "$(find "${tmp}" -name "*.pkg" -execdir echo '{}' ';' -print | sed -n 1p)" ]; then
-    
-    pkgfile=$(find "${tmp}" -name "*.pkg" -execdir echo '{}' ';' -print | sed -n 1p)
-    
+  if [ ! -s $(/usr/bin/find "${workDir}" -name "*.pkg") ]; then
+    echo "Error: No PKG found" && exit 1
   else
-    
-    echo "Error: No PKG found"
-    
-    exit 1
-    
+    PKGFilePath=$(/usr/bin/find "${workDir}" -name "*.pkg") && PKGFile=$(basename "${PKGFilePath}")
   fi
   
-  /usr/sbin/pkgutil --expand "${tmp}/${pkgfile}" "${expand}/${pkgfile}"
-  /usr/sbin/pkgutil --flatten "${expand}/${pkgfile}" "/Users/${currentuser}/Desktop/${pkgfile}"
+  /usr/sbin/pkgutil --expand "${PKGFilePath}" "${expandFolder}/${PKGFile}"
+  /usr/sbin/pkgutil --flatten "${expandFolder}/${PKGFile}" "${flattenFolder}/${PKGFile}"
   
-  echo "PKG fixed and saved at '/Users/${currentuser}/Desktop/${pkgfile}'"
-  
-  /bin/rm -rf "${tmp}"
-  
-exit 0
+  echo "Flat PKG saved at '${flattenFolder}/${PKGFile}'"
+  open -R "${flattenFolder}/${PKGFile}"
