Update pkgfixer

diff --git a/bin/pkgfixer b/bin/pkgfixer
--- a/bin/pkgfixer
+++ b/bin/pkgfixer
@@ -1,32 +1,33 @@
 #!/bin/bash
 
-  readonly prog_name=$(/usr/bin/basename ${0})
-  readonly prog_version="1.0"
+readonly prog_name=$(basename "${0}")
 
-  tmpDir=$(/usr/local/bin/tmpDir)
+string=$(openssl rand -hex 5)
+mkdir -p "$(getconf DARWIN_USER_TEMP_DIR)${string}"
+tmpDir=$(getconf DARWIN_USER_TEMP_DIR)${string}
 
-  expand_folder="${tmpDir}/expand_folder" && /bin/mkdir -p "${expand_folder}"
-  flatten_folder="${tmpDir}/flatten_folder" && /bin/mkdir -p "${flatten_folder}"
+expand_folder="${tmpDir}/expand_folder" && mkdir -p "${expand_folder}"
+flatten_folder="${tmpDir}/flatten_folder" && mkdir -p "${flatten_folder}"
 
-  pkg_arg="${1}"
+pkg_arg="${1}"
 
-  if [ ! -z "${1}" ]; then
-    echo "Process '${1}'"
-  else
-    echo "Error: Add PKG path as argument" && exit 1
-  fi
-  
-  /bin/cp -r "${pkg_arg}" "${tmpDir}/"
+if [ -n "${1}" ]; then
+  echo "Process '${1}'"
+else
+  echo "Error ${prog_name}: Add PKG path as argument" && exit 1
+fi
 
-  if [ ! -s $(/usr/bin/find "${tmpDir}" -name "*.pkg") ]; then
-    echo "Error: No PKG found" && exit 1
-  else
-    pkg_file_path=$(/usr/bin/find "${tmpDir}" -name "*.pkg")
-    pkg_file=$(/usr/bin/basename "${pkg_file_path}")
-  fi
+cp -r "${pkg_arg}" "${tmpDir}/"
 
-  /usr/sbin/pkgutil --expand "${pkg_file_path}" "${expand_folder}/${pkg_file}"
-  /usr/sbin/pkgutil --flatten "${expand_folder}/${pkg_file}" "${flatten_folder}/${pkg_file}"
+if [ ! -s "$(find "${tmpDir}" -name "*.pkg")" ]; then
+  echo "Error: No PKG found" && exit 1
+else
+  pkg_file_path=$(find "${tmpDir}" -name "*.pkg")
+  pkg_file=$(basename "${pkg_file_path}")
+fi
 
-  echo "Flat PKG saved at '${flatten_folder}/${pkg_file}'"
-  open -R "${flatten_folder}/${pkg_file}"
+pkgutil --expand "${pkg_file_path}" "${expand_folder}/${pkg_file}"
+pkgutil --flatten "${expand_folder}/${pkg_file}" "${flatten_folder}/${pkg_file}"
+
+echo "Flat PKG saved at '${flatten_folder}/${pkg_file}'"
+open -R "${flatten_folder}/${pkg_file}"
