Update

diff --git a/bin/pkgfixer b/bin/pkgfixer
--- a/bin/pkgfixer
+++ b/bin/pkgfixer
@@ -1,60 +1,60 @@
 #!/bin/bash
-	
-	currentuser=$(python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')
-	
-	if [ ! -z "${currentuser}" ]; then
-	
-		if [ -s "/Users/${currentuser}/.rnd" ]; then
-			
-			rm -rf "/Users/${currentuser}/.rnd"
-			
-		fi
-		
-	fi
-	
-	randstring=$(/usr/bin/openssl rand -hex 5)
-	
-	tmp="/private/tmp/${randstring}"
-	expand="${tmp}/expand"
-	flatten="${tmp}/flatten"
-	
-	/bin/mkdir -p "${tmp}"
-	/bin/mkdir -p "${expand}"
-	/bin/mkdir -p "${flatten}"
-		
-	arg="${1}"
-	
-	if [ ! -z "${1}" ]; then
-		
-		echo "Process '${1}'"
-		
-	else
-		
-		echo "Error: Add PKG path as argument"
-		
-		exit 1
-		
-	fi
-	
-	/bin/cp -r "${arg}" "${tmp}"/
-	
-	if [ ! -z "$(find "${tmp}" -name "*.pkg" -execdir echo '{}' ';' -print | sed -n 1p)" ]; then
-		
-		pkgfile=$(find "${tmp}" -name "*.pkg" -execdir echo '{}' ';' -print | sed -n 1p)
-		
-	else
-		
-		echo "Error: No PKG found"
-		
-		exit 1
-		
-	fi
-	
-	/usr/sbin/pkgutil --expand "${tmp}/${pkgfile}" "${expand}/${pkgfile}"
-	/usr/sbin/pkgutil --flatten "${expand}/${pkgfile}" "/Users/${currentuser}/Desktop/${pkgfile}"
-	
-	echo "PKG fixed and saved at '/Users/${currentuser}/Desktop/${pkgfile}'"
-	
-	/bin/rm -rf "${tmp}"
-	
+  
+  currentuser=$(python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')
+  
+  if [ ! -z "${currentuser}" ]; then
+  
+    if [ -s "/Users/${currentuser}/.rnd" ]; then
+      
+      rm -rf "/Users/${currentuser}/.rnd"
+      
+    fi
+    
+  fi
+  
+  randstring=$(/usr/bin/openssl rand -hex 5)
+  
+  tmp="/private/tmp/${randstring}"
+  expand="${tmp}/expand"
+  flatten="${tmp}/flatten"
+  
+  /bin/mkdir -p "${tmp}"
+  /bin/mkdir -p "${expand}"
+  /bin/mkdir -p "${flatten}"
+    
+  arg="${1}"
+  
+  if [ ! -z "${1}" ]; then
+    
+    echo "Process '${1}'"
+    
+  else
+    
+    echo "Error: Add PKG path as argument"
+    
+    exit 1
+    
+  fi
+  
+  /bin/cp -r "${arg}" "${tmp}"/
+  
+  if [ ! -z "$(find "${tmp}" -name "*.pkg" -execdir echo '{}' ';' -print | sed -n 1p)" ]; then
+    
+    pkgfile=$(find "${tmp}" -name "*.pkg" -execdir echo '{}' ';' -print | sed -n 1p)
+    
+  else
+    
+    echo "Error: No PKG found"
+    
+    exit 1
+    
+  fi
+  
+  /usr/sbin/pkgutil --expand "${tmp}/${pkgfile}" "${expand}/${pkgfile}"
+  /usr/sbin/pkgutil --flatten "${expand}/${pkgfile}" "/Users/${currentuser}/Desktop/${pkgfile}"
+  
+  echo "PKG fixed and saved at '/Users/${currentuser}/Desktop/${pkgfile}'"
+  
+  /bin/rm -rf "${tmp}"
+  
 exit 0
